version: '3.9'

services:
  postgres:
    container_name: next-blog-postgres
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - default

  redis:
    container_name: next-blog-redis
    image: redis:7.0.6
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redis:/data
    networks:
      - default

  zookeeper:
    container_name: next-blog-zookeeper
    image: 'bitnami/zookeeper:3.8.1'
    restart: always
    ports:
      - '${ZOOKEEPER_PORT}:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper:/bitnami
    networks:
      - default

  kafka:
    container_name: next-blog-kafka
    image: 'bitnami/kafka:3.4.0'
    restart: always
    ports:
      - '${KAFKA_PORT_EXTERNAL}:${KAFKA_PORT_EXTERNAL}'
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT_INTERNAL},CONTROLLER://:9093,EXTERNAL://:${KAFKA_PORT_EXTERNAL}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST_INTERNAL}:${KAFKA_PORT_INTERNAL},EXTERNAL://${KAFKA_HOST_EXTERNAL}:${KAFKA_PORT_EXTERNAL}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - default

  core-app:
    container_name: next-blog-core-app
    build:
      context: .
      dockerfile: ./apps/core-app/Dockerfile
      target: development
    image: next-blog-core-app:dev
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - kafka
      - postgres
      - redis
    env_file:
      - .env.docker-compose
    networks:
      - default

volumes:
  postgres:
  redis:
    driver: local
  kafka:
    driver: local
  zookeeper:
    driver: local

networks:
  default:
    driver: bridge
