version: '3.9'

include:
  - docker-compose-local.yml

services:
  core-app:
    container_name: next-blog-core-app
    build:
      context: .
      dockerfile: ./apps/core-app/Dockerfile
      target: build
    image: next-blog-core-app:build
    command: yarn test:e2e
    ports:
      - 3000:3000
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.docker-compose
    networks:
      - default
