version: '3.9'

include:
  - docker-compose-local.yml

services:
  core-app:
    container_name: next-blog-core-app
    build:
      context: .
      dockerfile: ./apps/core-app/Dockerfile
      target: production
    image: next-blog-core-app:prod
    ports:
      - 3000:3000
    depends_on:
      - kafka
      - postgres
      - redis
    env_file:
      - .env.docker-compose
    networks:
      - default

  notification:
    container_name: next-blog-notification
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: production
    image: next-blog-notification:prod
    depends_on:
      - kafka
      - postgres
      - redis
    env_file:
      - .env.docker-compose
    networks:
      - default

  ws-notification:
    container_name: next-blog-ws-notification
    build:
      context: .
      dockerfile: ./apps/ws-notification/Dockerfile
      target: production
    image: next-blog-ws-notification:prod
    ports:
      - 3001:3001
    depends_on:
      - kafka
      - redis
    env_file:
      - .env.docker-compose
    networks:
      - default

volumes:
  postgres:
  redis:
    driver: local
  kafka:
    driver: local
  zookeeper:
    driver: local

networks:
  default:
    driver: bridge
