version: '3.9'

services:
  postgres:
    container_name: next-blog-postgres
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - default

  redis:
    container_name: next-blog-redis
    image: redis:7.0.6
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redis:/data
    networks:
      - default

volumes:
  postgres:
  redis:
    driver: local

networks:
  default:
    driver: bridge
